#first stage
FROM node:16 AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

#second stage

FROM node:16-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist  
COPY --from=build /app/package*.json ./  

RUN npm install

EXPOSE 3000


CMD [ "npm","start" ]
