# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set environment variables using ENV for data customization
ENV TEXT1="hello"
ENV TEXT2="bharathi"
ENV TEXT3="how"
ENV TEXT4="are"
ENV TEXT5="you"

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the Python script into the container
COPY app.py .

# Install necessary dependencies (pandas)
RUN pip install pandas

# Command to run the Python script
ENTRYPOINT ["python", "app.py"]
